### ISSUE TITLE
Streaming

### ISSUE THREAD

**Issue by engelju** [benhoff/vexbot#16]
Hi, I have no idea how/where else to contact you, but I have always enjoyed your streams about vexbot.
Are you not doing them anymore?

**Comment by benhoff** [comment]
I'm hoping to start doing them again here in the near term! I was working on a video series for packt publishing which was taking up the time I was using for streaming but I just finished up with that

**Comment by engelju** [comment]
Ah alright, cool to know! Looking forward, then! :)
